name: CI

on:
  push:          # roda em todo push
  pull_request:  # e em todo PR

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout -----------------------------------------------------
    - uses: actions/checkout@v4

    # 2. Haskell tool-chain ------------------------------------------
    - name: Set up GHC + cabal
      uses: haskell/actions/setup@v3
      with:
        ghc-version: 9.4          # ou a versão que você usa
        cabal-version: latest     # ← corrigido

    # 3. Dependências de sistema -------------------------------------
    - name: Install alex, happy, graphviz, pytest
      run: |
        sudo apt-get update
        sudo apt-get install -y alex happy graphviz python3 python3-pytest

    # 4. Build executáveis -------------------------------------------
    - name: Build analysis (data-flow)
      run: make MODE=df           # gera ./analysis

    - name: Build analysis-ast
      run: make MODE=ast          # gera ./analysis-ast

    # 5. Testes -------------------------------------------------------
    - name: Run pytest suite
      run: pytest -q

    # 6. Artefatos DOT ------------------------------------------------
    - name: Upload DOTs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dot-files
        path: |
          test/output/**/*.dot
          test/golden-ast/*.dot
          test/golden-df/*.dot
