name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1) checkout
    - uses: actions/checkout@v4

    # 2) instala GHC e cabal
    - name: Set up Haskell
      uses: haskell/actions/setup@v2        # ←  repositório e tag existentes
      with:
        ghc-version: '9.4'                  # ajuste a versão que você usa
        cabal-version: 'latest'

    # 3) dependências de sistema
    - name: Install alex, happy, graphviz, pytest
      run: |
        sudo apt-get update
        sudo apt-get install -y alex happy graphviz python3 python3-pytest

    # 4) build data-flow
    - name: Build analysis (data-flow)
      run: make MODE=df            # gera ./analysis

    # 5) build AST
    - name: Build analysis-ast
      run: make MODE=ast           # gera ./analysis-ast

    # 6) pytest
    - name: Run pytest suite
      run: pytest -q

    # 7) salva artefatos DOT
    - name: Upload DOTs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dot-files
        path: |
          test/output/**/*.dot
          test/golden-ast/*.dot
          test/golden-df/*.dot
