name: CI

on:
  push:          
  pull_request:  

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # -------------------- 1. Checkout -------------------
    - uses: actions/checkout@v4

    # -------------------- 2. Haskell tool-chain ---------
    - name: Set up GHC + cabal
      uses: haskell/actions/setup@v3
      with:
        ghc-version: 9.4        # ajuste se usar outro
        cabal-version: latest4
        
    - name: Install alex, happy, graphviz, pytest
      run: |
        sudo apt-get update
        sudo apt-get install -y alex happy graphviz python3 python3-pytest
    - name: Build analysis (data-flow)
      run: make MODE=df         # gera ./analysis

    - name: Build analysis-ast
      run: make MODE=ast        # gera ./analysis-ast
    - name: Run pytest suite
      run: pytest -q
    - name: Upload DOTs (sempre)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dot-files
        path: |
          test/output/**/*.dot
          test/golden-ast/*.dot
          test/golden-df/*.dot
